### ISSUE TITLE
Each team member need clone repository

### ISSUE THREAD

**Issue by flipppp** [flipppp/devops-recepies#3]
- [x] Līga
- [x] Māris
- [ ] Mariko
- [x] Vineta
- [x] Ainārs

**Comment by mariissEU** [comment]
CLoned repo to local

**Comment by flipppp** [comment]
![Screenshot_6](https://github.com/flipppp/devops-recepies/assets/7150567/2051e001-329b-454b-9e19-e6887d443eaf)
![Screenshot_7](https://github.com/flipppp/devops-recepies/assets/7150567/eca29e72-cbf2-4950-b04b-200df01e307e)
![Screenshot_9](https://github.com/flipppp/devops-recepies/assets/7150567/a2112633-2135-4ea9-ae35-f3832403430b)
![Screenshot_10](https://github.com/flipppp/devops-recepies/assets/7150567/1d6c9735-d338-4a5d-919b-e1226ecbe472)
![Screenshot_11](https://github.com/flipppp/devops-recepies/assets/7150567/c98fd2cf-d2b6-4698-a764-2c81f06ff087)
![Screenshot_12](https://github.com/flipppp/devops-recepies/assets/7150567/0291dd5b-7c40-43b8-abb5-080f8d79a937)
![Screenshot_13](https://github.com/flipppp/devops-recepies/assets/7150567/0cf58774-dae6-4395-8174-633d1051a0e2)
![Screenshot_14](https://github.com/flipppp/devops-recepies/assets/7150567/30ba9321-56e5-4a2c-b82d-1a07f846a3be)
![Screenshot_15](https://github.com/flipppp/devops-recepies/assets/7150567/9bb71b41-de18-4e54-a060-23b57529203c)
