### ISSUE TITLE
Defined VOC

### ISSUE THREAD

**Issue by flipppp** [flipppp/devops-recepies#4]

**Comment by LiigaB** [comment]
VOC uzmetums, pirmie soļi:

1. Mērķis (Nodefinēt, ko mēs vēlamies iegūt ar VOC):
Piemēram - vēlamies uzzināt smalkāk, vai tāda mājaslapa būtu noderīga, kādas ir klientu tehniskās preferences. 

2. Potenciālie anketas jautājumi: 

Kvalitāte: 

1. Vai Jūs izmantotu šādu pakalpojumu? 
2. Vai Jums būtu svarīgi atsevišķi atzīmēt dietāros ierobežojumus (vegāns, veģetārietis, utt)?
3. Vai Jūs vēlētos 
4. Citi ieteikumi, viedokļi?

Ātrums: 

1. Kāds ir optimālais laiks, cik ilgi jūs gaidītu receptes saņemšanu pēc ievadītajiem datiem? 

Izmaksas: 
1. Vai Jūs būtu gatavs maksāt par pakalpojuma izmantošanu?
2. Cik Jūs būtu gatavs maksāt mēnesī?
