### ISSUE TITLE
Defined User stories

### ISSUE THREAD

**Issue by flipppp** [flipppp/devops-recepies#5]

**Comment by vinetaru** [comment]
Story 1

**Comment by flipppp** [comment]
As a clinic worker
I want to create appointments.
So that I can add doctor's note about the appointment

As a customer
I want to be able see all my appointment history.
So that I can get doctor's note about the appointment

**Comment by mariissEU** [comment]
Story 5
As a customer
I want to be able to see all doctors available.
So that I know who are working on animals
